/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateTasksArgs } from "./CreateTasksArgs";
import { UpdateTasksArgs } from "./UpdateTasksArgs";
import { DeleteTasksArgs } from "./DeleteTasksArgs";
import { TasksCountArgs } from "./TasksCountArgs";
import { TasksFindManyArgs } from "./TasksFindManyArgs";
import { TasksFindUniqueArgs } from "./TasksFindUniqueArgs";
import { Tasks } from "./Tasks";
import { User } from "../../user/base/User";
import { TasksService } from "../tasks.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Tasks)
export class TasksResolverBase {
  constructor(
    protected readonly service: TasksService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Tasks",
    action: "read",
    possession: "any",
  })
  async _tasksItemsMeta(
    @graphql.Args() args: TasksCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Tasks])
  @nestAccessControl.UseRoles({
    resource: "Tasks",
    action: "read",
    possession: "any",
  })
  async tasksItems(@graphql.Args() args: TasksFindManyArgs): Promise<Tasks[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Tasks, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Tasks",
    action: "read",
    possession: "own",
  })
  async tasks(
    @graphql.Args() args: TasksFindUniqueArgs
  ): Promise<Tasks | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Tasks)
  @nestAccessControl.UseRoles({
    resource: "Tasks",
    action: "create",
    possession: "any",
  })
  async createTasks(@graphql.Args() args: CreateTasksArgs): Promise<Tasks> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        user_id: args.data.user_id
          ? {
              connect: args.data.user_id,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Tasks)
  @nestAccessControl.UseRoles({
    resource: "Tasks",
    action: "update",
    possession: "any",
  })
  async updateTasks(
    @graphql.Args() args: UpdateTasksArgs
  ): Promise<Tasks | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          user_id: args.data.user_id
            ? {
                connect: args.data.user_id,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Tasks)
  @nestAccessControl.UseRoles({
    resource: "Tasks",
    action: "delete",
    possession: "any",
  })
  async deleteTasks(
    @graphql.Args() args: DeleteTasksArgs
  ): Promise<Tasks | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "userId",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async resolveFieldUserId(
    @graphql.Parent() parent: Tasks
  ): Promise<User | null> {
    const result = await this.service.getUserId(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
